FROM ubuntu
RUN apt-get update
RUN apt-get install -y nginx
RUN rm -f /etc/nginx/sites-enabled/default
COPY default /etc/nginx/sites-enabled/default
COPY 22.txt /var/www/html/22.txt
COPY 21.txt /var/www/html/21.txt
